# This bit is used to make sure we don't run too many pipelines:
# don't run the branch CI when a merge request is already open for the
# branch.
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

variables:
   GIT_CLONE_BASE: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}
   SANDBOX: /it/wave
   HOST: x86_64-linux
   ANOD_DEFAULT_SANDBOX_DIR: /it/wave

stages:
  - build

########################
## SETUP REPOSITORIES ##
########################

.setup: &setup_repos
    # This script expects $packages to be set to the list of packages to
    # retrieve from the build phase, and $subprojects to be set to the list
    # of subprojects to install in /tmp to be used by anod.

    # unpack the packages
    - cd $SANDBOX
    - mkdir -p fingerprints
    - for pkg in $packages; do
        if [ $pkg = "gnat" -o $pkg = "gnatall" ]; then
           anod install $pkg ;
           tar zxf $CI_PROJECT_DIR/gprbuild.tar.gz -C $HOST/$pkg ;
        else
           mkdir -p $HOST/$pkg ;
           tar zxf $CI_PROJECT_DIR/$pkg.tar.gz -C $HOST/$pkg ;
        fi ;
        touch fingerprints/$HOST.$pkg.install.json.assume-unchanged ;
        touch fingerprints/$HOST.$pkg.download-bin.json.assume-unchanged ;
      done
    - rm -f $CI_PROJECT_DIR/*.tar.gz

    # Figure out if we're on a sync branch
    - BRANCH=master
    - if [[ $CI_COMMIT_BRANCH =~ ^sync/ ]]; then
         BRANCH=$CI_COMMIT_BRANCH;
      elif [[ $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ ^sync/ ]]; then
         BRANCH=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME;
      fi

    # Setup the anod vcs for all subprojects.
    # For each repo, check if a branch with the same name as
    # $BRANCH exists; if so, use it.
    - for subproject in $subprojects ; do
         cd /tmp ;
         git clone $GIT_CLONE_BASE/eng/gpr/$subproject ;
         cd $subproject ;
         if `git show-ref $BRANCH > /dev/null` ; then
            git checkout $BRANCH ;
         fi ;
         if [ $subproject = "gprbuild-internal" ]; then
            anodrepo=gprbuild_testsuite ;
         else
            anodrepo=$subproject ;
         fi ;
         anod vcs --add-repo $anodrepo /tmp/$subproject ;
      done

###########
## BUILD ##
###########

build:
  services:
     - image:sandbox
     - cpu:8
     - mem:16
  stage: build
  script:
    # setup submodules
    - packages=""
    - subprojects="gprbuild gprconfig_kb"
    - *setup_repos

    # Setup the 'anod vcs' for this repo
    - anod vcs --add-repo gpr2-next $CI_PROJECT_DIR

    # Tune to use our build & test plan
    - anod tune --plan $CI_PROJECT_DIR/.ci.plan
    - anod run build

    # generate packages to be used at test stages.
    # Note: we can't package the full gnat or gnatall install as the size seems
    # to reach some limits for the saved artifacts. So we package gprbuild and
    # co and will amend the toolchains for testing..
    - for pkg in libgpr2-next; do
        echo "packaging $SANDBOX/$HOST/$pkg/install/" ;
        tar czf $CI_PROJECT_DIR/$pkg.tar.gz -C $SANDBOX/$HOST/$pkg/ install/ ;
      done
    - cd $CI_PROJECT_DIR
    - ls -l *.tar.gz

  artifacts:
    paths:
      - libgpr2-next.tar.gz
