include: '/.gitlab-ci-shared.yml'

stages:
  - build
  - test

###########
## BUILD ##
###########

build:
  extends: .job_template
  stage: build
  variables:
    JOB_SUBPROJECTS: eng/gpr/gprbuild eng/gpr/gprconfig_kb
  script:
    # Tune to use our build & test plan
    - anod tune --plan $CI_PROJECT_DIR/.ci.plan

    # and build it...
    - anod run build

    # generate packages to be used at test stages.
    - for pkg in gpr2-next libgpr2-next; do
        echo "packaging $SANDBOX/$HOST/$pkg/install/" ;
        tar czf $CI_PROJECT_DIR/$pkg.tar.gz -C $SANDBOX/$HOST/$pkg/ install/ ;
      done
    - cd $CI_PROJECT_DIR
    - ls -l *.tar.gz

  artifacts:
    paths:
      - gpr2-next.tar.gz
      - libgpr2-next.tar.gz
      - gpr1build.tar.gz

####################
## GPR2 TESTSUITE ##
####################

test_gpr2:
  extends: .test_template
  script:
    - setup_repos
    - install_packages gpr2-next libgpr2-next
    - run_testsuite gpr2 -Qnext test_gpr2
  artifacts:
    when:
      always
    paths:
      - testgpr2_result.xml
    reports:
      junit: testgpr2_result.xml

##############
## COVERAGE ##
##############

test_gpr2_cov:
  extends: .test_template
  script:
    - setup_repos
    - anod build gpr2 -Qcoverage,next
    # do a normal testsuite run but save the exit code instead of just exiting
    # so that coverage artifacts can be saved and used.
    - result=0
    - run_testsuite gpr2 -Qcoverage,next test_gpr2_cov || result=$?

    - mkdir $CI_PROJECT_DIR/coverage

    # save coverage results
    - mv $RESULTS_DIR/coverage-cobertura/cobertura.xml $CI_PROJECT_DIR/coverage/
    - mv $RESULTS_DIR/coverage-dhtml $CI_PROJECT_DIR/coverage/dhtml

    # display coverage stats for global reporting
    - echo_coverage_stats --coverage-file $RESULTS_DIR/coverage-xml/index.xml

    # report initial test status code
    - exit $result

  coverage: '/^Stmt Coverage:\s+(\d+\.\d+\%) \(\d+ \/ \d+\)$/'
  artifacts:
    when:
      always
    paths:
      - coverage/cobertura.xml
      - coverage/dhtml
      - testgpr2cov_result.xml
    reports:
      junit: testgpr2cov_result.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
