
------------------------------------------------------------------------------
--                                                                          --
--                            GPR PROJECT PARSER                            --
--                                                                          --
--            Copyright (C) 2015-2016, Free Software Foundation, Inc.       --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

--  DO NOT EDIT THIS IS AN AUTOGENERATED FILE







with System;

with Langkit_Support.Extensions;         use Langkit_Support.Extensions;
with Langkit_Support.Lexical_Env;
with Langkit_Support.Token_Data_Handler; use Langkit_Support.Token_Data_Handler;
with Langkit_Support.Tokens;             use Langkit_Support.Tokens;
with Langkit_Support.Vectors;

--  This package defines the base ("root") type for AST nodes. All node types
--  that appear in the AST derive from it.

package GPR_Parser.AST is

   -------------------
   -- Root AST node --
   -------------------

   type GPR_Node_Type is abstract tagged private;
   --  This "by-value" type is public to expose the fact that the various
   --  AST nodes are a hierarchy of tagged types, but it is not intended to be
   --  used directly, hence the "_Type" suffix. Please use instead the
   --  class-wide types such at the one below.

   type GPR_Node is access all GPR_Node_Type'Class;
   --  Most generic AST node type

   Property_Error : exception;
   --  Raised when an error occurs while evaluating a property.

   ----------------
   -- Extensions --
   ----------------

   --  Extensions are a way to associate arbitrary data (Extension_Type, i.e.
   --  pointers) to AST nodes.
   --
   --  In order to associate an extension to an AST node, one has first to
   --  register itself in Langkit_Support.Extensions to get an Extension_ID.
   --  Then, this ID must be passed to Get_Extension, which will create a slot
   --  to store this extension (or return an already existing one for the same
   --  ID). It is this slot that can be used to store arbitrary data.
   --
   --  As AST nodes can be deallocated later on, this abritrary data sometimes
   --  needs to be deallocated as well. The destructor mechanism was designed
   --  for this: when the AST node is about to be deallocated, the destructor
   --  callback is invoked so that one has a chance to release allocated
   --  resources.

   type Extension_Type is new System.Address;
   --  Data type storing arbitrary values in AST nodes

   type Extension_Access is access all Extension_Type;
   --  Access to the arbitrary values stored in AST nodes

   type Extension_Destructor is
     access procedure (Node      : GPR_Node;
                       Extension : Extension_Type)
     with Convention => C;
   --  Type for extension destructors. The parameter are the "Node" the
   --  extension was attached to and the "Extension" itself.

   function Get_Extension
     (Node : GPR_Node;
      ID   : Extension_ID;
      Dtor : Extension_Destructor) return Extension_Access;
   --  Get (and create if needed) the extension corresponding to ID for Node.
   --  If the extension is created, the Dtor destructor is associated to it.
   --  Note that the returned access is not guaranteed to stay valid after
   --  subsequent calls to Get_Extension.

   ----------------------------
   --  Environments handling --
   ----------------------------

   --  The following types and operations are implementation details we did not
   --  manage yet to put in a private part. Please don't use them.

   type Dummy_Metadata is new Integer;
   No_Metadata : constant Dummy_Metadata := 0;
   function Combine (L, R : Dummy_Metadata) return Dummy_Metadata is (0);
   --  This type and constants are added waiting for a real metadata type

   package AST_Envs is new Langkit_Support.Lexical_Env
     (GPR_Node,
      Dummy_Metadata,
      No_Metadata, Combine);

   subtype Env_Element is AST_Envs.Env_Element;
   No_Env_Element : constant Env_Element := (null, No_Metadata);

   

   

   type GPR_Node_Array is array (Positive range <>) of GPR_Node;
   type GPR_Node_Array_Record (N : Natural) is record
      Items : GPR_Node_Array (1 .. N);
   end record;

   type GPR_Node_Array_Access is access all GPR_Node_Array_Record;


   package GPR_Node_Vectors is new Langkit_Support.Vectors
     (GPR_Node);

   function Get
     (T       : GPR_Node_Array_Access;
      Index   : Natural;
      Or_Null : Boolean := False) return GPR_Node
   is
     (if Index < T.Items'Length
      then T.Items (Index + 1)
      else (if Or_Null
            then null
            else raise Property_Error));



   package GPR_Node_Arrays renames
     GPR_Node_Vectors.Elements_Arrays;

   procedure Populate_Lexical_Env
     (Node : GPR_Node; Root_Env : AST_Envs.Lexical_Env);
   --  Populate the lexical environment for node and all its children

   -----------------------------
   -- Miscellanous operations --
   -----------------------------

   type GPR_Node_Type_Kind is new Natural;
   --  Describe the concrete type (aka dynamic type) of an AST node (i.e. from
   --  which concrete derivation it comes from).
   --  See GPR_Parser.AST for possible values.

   function Kind (Node : access GPR_Node_Type)
                  return GPR_Node_Type_Kind is abstract;
   function Kind_Name
     (Node : access GPR_Node_Type) return String is abstract;
   --  Return the concrete kind for Node

   procedure Destroy
     (Node : access GPR_Node_Type) is abstract;
   --  Free the resources allocated to this node and all its children.
   --
   --  This is an internal implementation detail, please don't use this.
   --  TODO??? Hide it somehow: destruction is done automatically when the
   --  owning analysis unit is destroyed itself.

   -------------------------------
   -- Tree traversal operations --
   -------------------------------

   function Child_Count (Node : access GPR_Node_Type)
                         return Natural is abstract;
   --  Return the number of children Node has

   procedure Get_Child (Node   : access GPR_Node_Type;
                        Index  : Natural;
                        Exists : out Boolean;
                        Result : out GPR_Node) is abstract;
   --  Get the Index'th child of Node, storing it into Result. Store in Exists
   --  whether Node had such a child (if not, the content of Result is
   --  undefined).

   function Child (Node  : access GPR_Node_Type'Class;
                   Index : Natural) return GPR_Node;
   --  Return the Index'th child of Node, or null if Node has no such child

   function Children
     (Node : access GPR_Node_Type'Class)
     return GPR_Node_Arrays.Array_Type;
   --  Return an array containing all the children of Node.
   --  This is an alternative to the Child/Child_Count pair, useful if you want
   --  the convenience of ada arrays, and you don't care about the small
   --  performance hit of creating an array.

   type Visit_Status is (Into, Over, Stop);
   --  Helper type to control the AST node traversal process. See Traverse.

   function Traverse
     (Node  : GPR_Node;
      Visit : access function (Node : GPR_Node)
                               return Visit_Status)
     return Visit_Status;
   --  Given the parent node for a subtree, traverse all syntactic nodes of
   --  this tree, calling the given function on each node in pre order (ie.
   --  top-down). The order of traversing subtrees follows the order of
   --  declaration of the corresponding attributes in the grammar. The
   --  traversal is controlled as follows by the result returned by Visit:
   --
   --     Into   The traversal continues normally with the syntactic
   --            children of the node just processed.
   --
   --     Over   The children of the node just processed are skipped and
   --            excluded from the traversal, but otherwise processing
   --            continues elsewhere in the tree.
   --
   --     Stop   The entire traversal is immediately abandoned, and the
   --            original call to Traverse returns Stop.

   procedure Traverse
     (Node  : GPR_Node;
      Visit : access function (Node : GPR_Node)
              return Visit_Status);
   --  This is the same as Traverse function except that no result is returned
   --  i.e. the Traverse function is called and the result is simply discarded.

   function Parents
     (Node : access GPR_Node_Type)
      return GPR_Node_Array_Access;
   --  Return the list of parents for this node (this node included)

   ----------------------------------------
   -- Source location-related operations --
   ----------------------------------------

   function Sloc_Range (Node : GPR_Node;
                        Snap : Boolean := False) return Source_Location_Range;
   --  Return the source location range corresponding to the set of tokens from
   --  which Node was parsed.
   --
   --  TODO??? Document the Snap formal.

   function Compare (Node : GPR_Node;
                     Sloc : Source_Location;
                     Snap : Boolean := False) return Relative_Position;
   --  Compare Sloc to the sloc range of Node.
   --
   --  TODO??? Document the Snap formal.

   function Lookup (Node : GPR_Node;
                    Sloc : Source_Location;
                    Snap : Boolean := False) return GPR_Node;
   --  Look for the bottom-most AST node whose sloc range contains Sloc. Return
   --  it, or null if no such node was found.
   --
   --  TODO??? Document the Snap formal.

   -----------------------
   -- Lexical utilities --
   -----------------------

   type Child_Or_Trivia is (Child, Trivia);
   --  Discriminator for the Child_Record type

   type Child_Record (Kind : Child_Or_Trivia := Child) is record
      case Kind is
         when Child =>
            Node : GPR_Node;
         when Trivia =>
            Trivia : Token;
      end case;
   end record;
   --  Variant that holds either an AST node or a token

   package Children_Vectors is new Langkit_Support.Vectors (Child_Record);
   package Children_Arrays renames Children_Vectors.Elements_Arrays;

   function Children_With_Trivia
     (Node : GPR_Node) return Children_Arrays.Array_Type;
   --  Return the children of this node interleaved with Trivia token nodes, so
   --  that:
   --  - Every trivia contained between Node.Start_Token and Node.End_Token - 1
   --    will be part of the returned array;
   --  - Nodes and trivias will be lexically ordered.

   function Token_Start (Node : GPR_Node) return Natural;
   --  Return the index of the first token used to parse Node

   function Token_End (Node : GPR_Node) return Natural;
   --  Return the index of the last token used to parse Node

   -------------------
   -- Debug helpers --
   -------------------

   function Image
     (Node : access GPR_Node_Type) return String is abstract;
   --  Debug helper: return a textual representation of this node and all its
   --  children.

   function Short_Image (Node : GPR_Node) return String;
   --  Debug helper: return a short representation of the string, containing
   --  just the kind name and the sloc.

   procedure Print (Node  : access GPR_Node_Type;
                    Level : Natural := 0) is abstract;
   --  Debug helper: print to standard output Node and all its children. Level
   --  indicates the indentation level for the output.

   procedure PP_Trivia (Node : GPR_Node; Level : Integer := 0);
   --  Debug helper: print to standard output Node and all its children along
   --  with the trivia associated to them. Level indicates the indentation
   --  level for the output.

   procedure Dump_Lexical_Env
     (Node : GPR_Node; Root_Env : AST_Envs.Lexical_Env);
   --  Debug helper: dump the lexical environment of Node, and consequently any
   --  nested lexical environment. Used for debugging/testing purpose. Pass the
   --  root env explicitly so that we can tag it properly in the output.

   procedure Dump_One_Lexical_Env
     (Self : AST_Envs.Lexical_Env;
      Env_Id : String := "";
      Parent_Env_Id : String := "");
   --  Debug helper: Dumps one lexical env. You can supply ids for env and its
   --  parent, so that they will be identified in the output.

private

   --------------------------
   -- Extensions internals --
   --------------------------

   type Extension_Slot is record
      ID        : Extension_ID;
      Extension : Extension_Access;
      Dtor      : Extension_Destructor;
   end record;
   --  TODO??? Remove this from the public API

   package Extension_Vectors is new Langkit_Support.Vectors
     (Element_Type => Extension_Slot);

   -------------------------------
   -- Root AST node (internals) --
   -------------------------------

   type GPR_Node_Type is abstract tagged record
      Parent                 : GPR_Node := null;
      Token_Data             : Token_Data_Handler_Access := null;
      Token_Start, Token_End : Natural  := 0;
      Parent_Env             : AST_Envs.Lexical_Env;
      Extensions             : Extension_Vectors.Vector;
   end record;
   --  TODO??? Remove this from the public API

   procedure Free_Extensions (Node : access GPR_Node_Type);
   --  Implementation helper to free the extensions associatde to Node

   function Is_Empty_List
     (Node : access GPR_Node_Type)
      return Boolean is
     (False);
   --  Return whether Node is an empty list (so this is wrong for all nodes
   --  that are not lists).

   function Do_Env_Actions
     (Self       : access GPR_Node_Type;
      Parent_Env : in out AST_Envs.Lexical_Env) return AST_Envs.Lexical_Env
   is (null);
   --  Internal procedure that will execute all necessary lexical env actions
   --  for Node. This is meant to be called by Populate_Lexical_Env, and not by
   --  the user.
   --
   --  Parent_Env is the environment that is the parent scope for Self when
   --  entering the function. It is an in out parameter because the
   --  implementation can replace Parent_Env by a new Lexical_Env derived from
   --  it.
   --
   --  The return value can be either null, or a new Lexical_Env that represent
   --  a new scope that will be used by Self's children.
   --  The difference between replacing Parent_Env and returning a new env, is
   --  that replacing Parent_Env will affect the env that the following
   --  siblings of Self see, while returning a new env will only affect the
   --  environment seen by Self's children.

   function Lookup_Children
     (Node : access GPR_Node_Type;
      Sloc : Source_Location;
      Snap : Boolean := False) return GPR_Node
   is (raise Program_Error);
   --  Implementation helper for the looking up process.
   --
   --  This should be an abstract primitive, but it's not possible to have a
   --  private abstract primitive, so we provide a default implementation that
   --  raises a Program_Error. This is consistent as this default
   --  implementation is never supposed to be called. However, we lost the
   --  capacity to detect at compile time that this is not overriden.

   procedure Lookup_Relative (Node       : GPR_Node;
                              Sloc       : Source_Location;
                              Position   : out Relative_Position;
                              Node_Found : out GPR_Node;
                              Snap       : Boolean := False);
   --  Implementation helper for the looking up process. TODO??? Do not expose
   --  it in the public API.

   function Token_Start (Node : GPR_Node) return Natural is
     (Node.Token_Start);
   function Token_End (Node : GPR_Node) return Natural is
     (Node.Token_End);

end GPR_Parser.AST;
