
------------------------------------------------------------------------------
--                                                                          --
--                            GPR PROJECT PARSER                            --
--                                                                          --
--            Copyright (C) 2015-2016, Free Software Foundation, Inc.       --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

--  DO NOT EDIT THIS IS AN AUTOGENERATED FILE


with Langkit_Support.Bump_Ptr.Vectors;
with Langkit_Support.Tokens; use Langkit_Support.Tokens;

--  Generic package to create AST node types that just contain lists of other
--  AST node types.
--
--  This package is not part of the public API.

private generic
   type Node_Type is abstract new GPR_Node_Type with private;
   type Node_Access is access all Node_Type'Class;
package GPR_Parser.AST.List is

   --  See AST_Root for primitive operations documentations.
   --
   --  Note that as this package is instantiated in private parts and is itself
   --  private, there is no real need to create a private part here.

   List_Kind : constant GPR_Node_Type_Kind := 1;

   package Node_Vectors is new Langkit_Support.Bump_Ptr.Vectors
     (Element_Type => Node_Access);

   type List_Type is new GPR_Node_Type with record
      Vec : Node_Vectors.Vector;
   end record;

   overriding
   function Kind (Node : access List_Type) return GPR_Node_Type_Kind;
   overriding
   function Kind_Name (Node : access List_Type) return String;
   overriding
   function Image (Node : access List_Type) return String;

   overriding
   function Child_Count (Node : access List_Type)
                         return Natural;
   overriding
   procedure Get_Child (Node   : access List_Type;
                        Index  : Natural;
                        Exists : out Boolean;
                        Result : out GPR_Node);

   overriding
   procedure Print (Node  : access List_Type;
                    Level : Natural := 0);

   overriding
   function Lookup_Children
     (Node : access List_Type;
      Sloc : Source_Location;
      Snap : Boolean := False) return GPR_Node;

   overriding procedure Destroy (Node : access List_Type);

end GPR_Parser.AST.List;
