
------------------------------------------------------------------------------
--                                                                          --
--                            GPR PROJECT PARSER                            --
--                                                                          --
--            Copyright (C) 2015-2016, Free Software Foundation, Inc.       --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

--  DO NOT EDIT THIS IS AN AUTOGENERATED FILE




with GPR_Parser.Analysis.C;
use GPR_Parser.Analysis.C;

--  This package defines data types and subprograms to provide the
--  implementation of the exported C API for AST nodes.
--
--  Unless one wants to deal with C code, it is very likely that one needs to
--  use this package. Please refer to the C header if you want to use the C
--  API.

package GPR_Parser.AST.C is

   function Wrap (Token : Token_Type) return gpr_token;
   function Unwrap (Token : gpr_token) return Token_Type;

   



type gpr_gpr_node_array_Ptr is access GPR_Node_Array_Access;

procedure gpr_gpr_node_array_dec_ref (A : GPR_Node_Array_Access)
   with Export        => True,
        Convention    => C,
        External_name => "gpr_gpr_node_array_dec_ref";



   ------------------------------------
   -- Lexical environment primitives --
   ------------------------------------

   



type gpr_lexical_env_array_Ptr is access Lexical_Env_Array_Access;

procedure gpr_lexical_env_array_dec_ref (A : Lexical_Env_Array_Access)
   with Export        => True,
        Convention    => C,
        External_name => "gpr_lexical_env_array_dec_ref";



   function gpr_lexical_env_parent
     (Env : gpr_lexical_env)
      return gpr_lexical_env
      with Export        => True,
           Convention    => C,
           External_name => "gpr_lexical_env_parent";

   function gpr_lexical_env_node
     (Env : gpr_lexical_env)
      return gpr_base_node
      with Export        => True,
           Convention    => C,
           External_name => "gpr_lexical_env_node";

   function gpr_lexical_env_get
     (Env  : gpr_lexical_env;
      Name : gpr_text)
      return Env_Element_Array_Access
      with Export        => True,
           Convention    => C,
           External_name => "gpr_lexical_env_get";

   procedure gpr_lexical_env_dec_ref
     (Env : gpr_lexical_env)
      with Export        => True,
           Convention    => C,
           External_name => "gpr_lexical_env_dec_ref";

end GPR_Parser.AST.C;
