
------------------------------------------------------------------------------
--                                                                          --
--                            GPR PROJECT PARSER                            --
--                                                                          --
--            Copyright (C) 2015-2016, Free Software Foundation, Inc.       --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

--  DO NOT EDIT THIS IS AN AUTOGENERATED FILE


with Ada.Text_IO; use Ada.Text_IO;
with Ada.Unchecked_Conversion;

with System;

with Langkit_Support.Slocs; use Langkit_Support.Slocs;
with Langkit_Support.Text;  use Langkit_Support.Text;

with GPR_Parser.Analysis_Interfaces;
use GPR_Parser.Analysis_Interfaces;

package body GPR_Parser.Debug is

   --------
   -- PN --
   --------

   procedure PN (Node : GPR_Node) is
   begin
      Put_Line (Image (Node.Short_Image));
   end PN;

   --------
   -- PT --
   --------

   procedure PT (Node : GPR_Node) is
   begin
      Node.Print;
   end PT;

   ----------
   -- PTok --
   ----------

   procedure PTok (Node : GPR_Node; T : Token_Index) is
      --  TODO??? This is very kludgy: in order to workaround visibility
      --  issues, we do gory unsafe conversion in order to turn token indices
      --  into token records.
      --
      --  We should get rid of this fixing GDB to make it easier to call
      --  tagged types primitives. This way we will be able to invoke regular
      --  AST node primitives directly from GDB to get token records.

      type Dummy_Node is tagged record
         Parent : System.Address;
         Unit   : Analysis_Unit_Interface;
      end record;

      type Dummy_Node_Access is access Dummy_Node;

      type Dummy_Token_Type is record
         TDH           : Token_Data_Handler_Access;
         Token, Trivia : Token_Index;
      end record;

      function Convert is new Ada.Unchecked_Conversion
        (Dummy_Token_Type, Token_Type);
      function Convert is new Ada.Unchecked_Conversion
        (GPR_Node, Dummy_Node_Access);

      N   : constant Dummy_Node_Access := Convert (Node);
      Tok : constant Token_Type :=
         Convert ((TDH    => N.Unit.Token_Data,
                   Token  => T,
                   Trivia => No_Token_Index));
      D : constant Token_Data_Type := Data (Tok);

   begin
      Put (Token_Kind_Name (D.Kind));
      if D.Text /= null then
         Put (" " & Image (D.Text.all, With_Quotes => True));
      end if;
      Put_Line (" [" & Image (D.Sloc_Range) & "]");
   end PTok;

end GPR_Parser.Debug;
