
/*----------------------------------------------------------------------------
--                                                                          --
--                            GPR PROJECT PARSER                            --
--                                                                          --
--            Copyright (C) 2015-2017, Free Software Foundation, Inc.       --
--                                                                          --
-- This library is free software;  you can redistribute it and/or modify it --
-- under terms of the  GNU General Public License  as published by the Free --
-- Software  Foundation;  either version 3,  or (at your  option) any later --
-- version. This library is distributed in the hope that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                            --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
----------------------------------------------------------------------------*/

/*  DO NOT EDIT THIS IS AN AUTOGENERATED FILE */


#ifndef QUEX_INTERFACE_H
#define QUEX_INTERFACE_H

#include <stdint.h>

struct token {
  /* Kind for this token (identifier, keyword, ...). */
  uint16_t id;
  /* For token kinds that don't keep text, NULL.  Pointer to an
     UTF-32-encoded string otherwise (native endianity). */
  const uint32_t *text;
  /* Size (in 32-bit words) for text. */
  size_t text_length;
  /* Source location for this token.  */
  uint32_t start_line, end_line;
  uint16_t start_column, end_column;
  uint32_t offset;
};

typedef struct Lexer Lexer;

Lexer *gpr_lexer_from_buffer(uint32_t *buffer, size_t length);

void gpr_free_lexer(Lexer *lexer);

int gpr_next_token(Lexer *lexer, struct token *tok);

#endif
